resoai/TileBoard

README.md

Updates to the README documentation for CONFIG object, pages, groups, and tiles.

README documentation cleanup/updates

---

README.md
config.js
scripts/directives.js
styles/main.less

CSS on the AM/PM might need a little perfection, but this change worked for me.

Adding timeFormat options  12 or 24 hour time.

---

README.md

Update README with examples of events

Update README with events details

---

README.md

Adds information on toast notifications to README

Add notification documentation

---

README.md

Add screensaver documentation to README.md

Add screensaver info to README

---

index.html

Small typo fix for weather low temperature line

Fix missing quote

---

scripts/app.js
scripts/init.js
scripts/models/api.js

Support new Home Assistant Authentication API

OAuth2 support #134

---

README.md

Adding `customStyles` docs

---

scripts/controllers/main.js

UI build in into Home Assistant uses different domains to trigger scripts and switches.

Changed domain to one used by HASS

---

scripts/controllers/main.js

replace vacuum.stop with vacuum.return_to_base

---

index.html
styles/main.css

Weather: Swap low/high daily temperature text with down/up arrows

---

index.html
scripts/controllers/main.js
styles/main.css

Home Assistant supports the `armed_night` state. This PR adds support for this state to the Alarm card.

Add support for armed_night state

---

README.md
config.example.js
scripts/app.js
scripts/controllers/main.js

I added Mapbox as an available option for the device tracker tile, as it has high free usage limits and better options.

Adde Mapbox map type

---

scripts/app.js
scripts/controllers/main.js
scripts/directives.js
scripts/models/api.js

This resolves https://github.com/resoai/TileBoard/issues/233 by adding checks in several places to see if the URL is relative or not

Added check for several BG images to determine if they are local or not

---

index.html
styles/main.css

- new property 'iconTitle' in weather list
- new css classes for styling of 'iconTitle' and 'primaryTitle' with defaults in main.css
- .weather-list-header--primary
- .weather-list--primary

More configurable weather list header

---

index.html
scripts/controllers/main.js
scripts/directives.js
scripts/init.js
scripts/models/api.js

This allows for injecting angular objects like `$http` which:
a) other changes will depend on.
b) currently used plain XHR should be replaced with it.

Convert Api class into angular.js service (provider)

---

scripts/models/api.js

Use promises/$q to make code flow easier to follow.

Refactor token fetching to not use callbacks

---

scripts/models/api.js

Fix usage of return value from $q

---

index.html
styles/main.css
styles/main.less

Suggestion on how to make the close button look better in popups - introduced a titlebar area that fits both the close button and entity's title. Tell me what you think.
Changes in main.less might be a bit messy as I don't fully understand currently used convention (is it BEM, custom convention or a mix?).
@akloeckner

Add title bar area to popups

---

README.md
config.example.js
scripts/controllers/main.js

To allow calling APIs like `getUser`.

Expose Api service on context

---

TILE_EXAMPLES.md
index.html
scripts/controllers/main.js

Also added missing documentation for POPUP_IFRAME tile.
Resolves #272

Allow specifying customHtml as function

---

README.md

I simply merged the two descriptions...

remove duplicate `classes` documentation

---

scripts/directives.js

Improvement on https://github.com/resoai/TileBoard/pull/362

Use toAbsoluteServerURL for HLS video url

---

TILE_EXAMPLES.md
index.html
scripts/controllers/main.js

Unfortunately I have no way of testing it at all, please fell free to change anything you fell looks wrong.

Add HVAC mode support to climate tile

---

styles/main.less

Since there was no color defined for GAUGE tile, I've picked some. Not sure if it's nice or not but it's better than default gray I guess.

Pick some color for gauge tile

---

scripts/controllers/main.js

Fix backwards compatibility with openPopup

---

config.example.js
index.html

Also add some examples to the example config.
Resolves #349

Read "dateFormat" for HEADER_ITEMS.DATE, same as for DATETIME

---

README.md
TILE_EXAMPLES.md
scripts/controllers/main.js

Resolves #416
Disclaimer: Haven't tested it.

Add support for passing variables when running scripts

---

scripts/controllers/main.js
scripts/models/api.js

Create "callService" to replace "sendItemData" and have less repetition

---

.eslintrc.yaml
package.json
scripts/controllers/main.js
scripts/controllers/noty.js
scripts/controllers/screensaver.js
scripts/directives.js
scripts/globals.js
scripts/globals/constants.js
scripts/globals/utils.js
scripts/index.js
scripts/init.js
scripts/models/api.js
scripts/models/noty.js

Those changes were done mostly automatically by `eslint --fix` command.
There should be no functional changes.
@akloeckner

Fix linting issues and enable more eslint rules to enforce consistency

---

scripts/models/api.js

Disconnect websocket connection on closing/reloading page

---

.eslintrc.yaml
scripts/controllers/main.js
scripts/controllers/noty.js
scripts/directives.js
scripts/globals/utils.js

Annotations are not needed (in most places at least) as that is handled
by ng-annotations babel plugin automatically.

Fix some style and remove unnecessary directive annotations

---

CONTRIBUTING.md
commitlint.config.js
package-lock.json
package.json

For more info see:
- https://www.conventionalcommits.org/
- https://github.com/conventional-changelog/commitlint
- https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-angular
@akloeckner

chore: enforce conventionalcommits convention for commit messages

---

styles/main.less

fix: camera title extending beyong tile boundaries

---

index.html.ejs
scripts/controllers/main.js
styles/main.less

Here comes the next refactor to make more use of the modular popup.
* use modular popup and remove legacy code
* make camera not freeze when on popup
* add timeout to modular popup
I don't see any breaking changes with this.
Fixes #447

refactor: use modular popup for door entry

---

index.html.ejs
package.json
rollup.config.js
scripts/index.js
yarn.lock

fix: bundle with mdi fonts instead of loading from external server

---

index.html.ejs
scripts/controllers/main.js
scripts/globals/constants.js

fix: enable arm buttons based on supported alarm features

---

manifest.webmanifest

see here: https://webplatform.news/issues/2020-08-25

fix: app not installable on firefox

---

scripts/controllers/main.js
styles/main.less

fixes #423
this uses the first approach suggested in the issue.
I just couldn't get the other one to work...

fix: fullsize popup cropped at the bottom

---

styles/themes.less

fix(HOMEKIT): make colors of ON tiles consistent

---

package.json
yarn.lock

fix(dev): don't lint unstaged changes on commit
fix(dev): automatically fix eslint errors in changed files on commit
@akloeckner

Linting improvement on committing

---

scripts/globals/utils.js

also export the moment class to user space
this will enable the user to do
```
moment.locale('de');
```
in their `config.js`.

feat: use moment.js for timeAgo

---

scripts/controllers/main.js

Fixes #496 
See also #509 
This allows users to use the popup timeout feature themselves as outlined in #496 .

fix(popup): popup timeout now accessible to user on $scope

---

TILE_EXAMPLES.md

Added additional text to #### IMAGE

docs(IMAGE): link to example QR code generator

---

README.md
TILE_EXAMPLES.md
config.example.js
index.html.ejs
scripts/controllers/main.js
scripts/directives/headerItem.html
scripts/directives/tile.html
styles/main.less
styles/themes.less

- added filters to localize numeric values according to locale
- changes in CLIMATE tile
- added function filterNumber in $scope to call from anonymous functions (existing function numberFilter does not use locale)

feat(WEATHER): localized number values and support "pressure" key

---

config.example.js

Added partlycloudy to HEADER_ITEMS.WEATHER
Was not showing any icon before

Added partlycloudy to HEADER_ITEMS.WEATHER

---

rollup.config.js

Added Danish locales to rollup.config.js
I have tested it, and it worked flawless on my own fork.

Added Danish locales to rollup.config.js

---

.dockerignore
.github/workflows/on_push.yaml
.github/workflows/on_tag.yaml
docker/00-check-config.sh
docker/Dockerfile
docker/Dockerfile.build
docker/Dockerfile.run
docker/README.md

Hi,
I noticed there's no official docker build for the project. The below is a simple build which serves using `nginx:alpine`. If you'd like to set up an official repository, let me know and I can update the repository name in the readme below.
chetan

feat: create docker images for standalone use

---

scripts/controllers/main-utilities.js

fix: programmatic openPopup can end up with dead tiles
