resoai/TileBoard

- tile.html
The sensor tile would only show a unit if `unit:` was defined in the JS configuration. This fix allows it to show the default unit_of_measurement from HomeAssistant if a `unit:` is not defined in JS.
> Fix for sensor tile unit_of_measurement

- scripts/main-controller.js
Replacing 'includes' with 'indexOf' to support Internet Explorer 11 and other older browsers. Other browsers still work. Work-around documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Browser_compatibility
> Replacing 'includes' with 'indexOf' to support Internet Explorer 11 and other older browsers

- index.html
On iOS the tileboard can now be added to the frontscreen at full-screen mode.
Code is from https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html.
> Add iOS full-screen mode

- styles/main.css
- styles/main.less
- styles/themes.css
- styles/themes.less
The only reason for this change is to prepare code for future fix.
It should be almost equally visually to previous code.
Previous code applied bottom offset to bottom-positioned page menu which
created a gap that would let clicks go through it if page was scrolled.
Using padding instead makes sure there is no gap there and also allows
to created better scrolling indicator in the future.
> Use padding in bottom-positioned pages-menu instead of bottom offset

- index.html
- scripts/controllers/main.js
- scripts/directives.js
- styles/main.css
- styles/main.less
- styles/themes.css
- styles/themes.less
To clearly indicate that the area under page menu is not clickable when
there are tiles underneath, darken its barkgroung when page is scrolled either
vertically (with page menu on the bottom) or horizontally (page menu on the left).
> Darken transparent page menu background when page is scrolled (#104)

- README.md
- config.example.js
- scripts/controllers/main.js
Just wanted to clean up console which helps especially when developing.
I own a motion sensor that sends state changes for 6 different entities every
few seconds. That makes it easy to miss errors in the console.
> Disable debug console logs by default

- README.md
Home Assistant needs to be restarted the first time that the `www` folder is created.
> Update instructions to include restarting Home Assistant

- index.html
By default the cover tile disables the `open` control in case the
entity state is already set to `open`. This might be OK for covers
without positioning details, but not for covers which report their
position back to HA.
Thus, this change will enhance the `open` control to support covers with
partial positions. It will change the behaviour of the `open` control
in the following way. With this change, the `open` control will only be
disabled when:
1. The state is `open` and there's no `current_position` attribute (legacy / backward compatibility)
2. The state is `open` and the `current_position` attribute equals `100` (new position support)
> Fix for partially opened covers #164

- scripts/controllers/main.js
Just like the LightSliderConf, allow the configuration to include a `field` and use that as the attribute name to be used for the value of the slider.
This is the same the is being done in `getLightSliderConf`, so seems suitable in that context, if I understood everything correctly. This was my approach to solve #209, but I may have overlooked "the proper way", maybe?
> Use `field` mechanism for value in sliders

- index.html
- scripts/controllers/main.js
- styles/main.css
- styles/main.less
Changed color picker to be a config option for lights rather than
implicitly diplayed if entity has rgb_color attribute (though they will
not do anything in HA if entity does not have rgb_color attribute).
Fixed bug so that color picker can be used when sliders are not being
used. Fixed margins to better match sliders.
if light config has the following then color picker will be displayed on the longpress view:
```
colorpicker: true,
```
Perhaps future changes will have the colorpicker configuration to be more like sliders and allow you to specify which attribute to update, which type of color values to use (RBG, HEX, or HLSA), etc. I only have one color changing bulb to test with, others may be different.
> Changed color picker to be config option rather than implicit

- scripts/controllers/main.js
I use direct links for facebook profile pictures and entity picture and the tracks keeps appending the server url to it. Small fix working locally.
> Fully qualified entity_picture url

- index.html
This was making writing anonymous methods for the line section of the weather module much more difficult.
> Fix item and entity not being passed to getWeatherLine

- scripts/controllers/main.js
Since `getMonth()` returns 0-based month, we need to add 1 to get
current month.
Resolves #235
> fix: wrong initial month in INPUT_DATETIME picker

- scripts/controllers/main.js
This alters the `item.state(s)` fallback logic, in order for the following to work:
```
state: function (item, entity) {
return entity.attributes.can_cancel ? entity.state : null;
},
```
The purpose is to remove the state field from tiles of one-shot scripts, which have no meaningful state.
The new fallback falls in line with the 'highly customizable' objective of TileBoard:
* if the user provides `state` or `states`, the field is used - no matter what, so also `null`, `false`, `{}` or similar results.
* if the user provides sth, which is not a function, string or object, it is simply passed on as the state.
* if none of the fields are provided, the `entity.state` is returned.
I believe this is very similar to the old logic, but more consistent and more customizable. However, people might …
> Fix item's state behavior

- scripts/models/api.js
When HomeAssistant is restarting or just there is a problem with
connection, TileBoard assumed that user needs to get authenticated
and tried to fetch new token after deleting current one.
Don't do that unless the response code is in 4xx range.
Per HomeAssistant documentation[1], it will return 400, 401 or 403
when token is expired or there is other authentication error.
Also don't react to state changes until response is in DONE state.
[1] https://developers.home-assistant.io/docs/en/auth_api.html#making-authenticated-requests
> Don't clear access token on intermittent connection problem

- scripts/models/api.js
To avoid `oauth` and `code` getting duplicated and filling up the URL,
remove them after authenticating and redirecting back to TileBoard.
Use `$location` service to read and change query params. Allows to
remove crazy custom code for getting params and makes things much neater.
This PR also includes minor naming changes:
- _request() => _tokenRequest()
- url => data
New names better convey their actual purpose.
Resolves #279
> Remove oauth params from URL after authenticating

- scripts/init.js
Use same settings for both "tooltips" and "hover" so that when tooltip
is shown for certain data point, also the "point" for it is showing up.
@akloeckner
> Fix points not showing up when hovering chart values

- README.md
- index.html
- scripts/controllers/main.js
- scripts/init.js
- scripts/models/api.js
This adds support for showing multiple entities in the chart.
- Nothing should change for single entities
- With multiple entities, all using the same value unit (like degrees or watts), there will be a single y-axis scaled to accommodate all values. That's a perfect case.
- With multiple entities with different value units or with non-continuous data, there will be multiple y-axes added. That's not an ideal situation and not really possible to handle perfectly. Ideally, there should be multiple graphs created for those cases. But it's sort of usable and if users want to do that, it's up to them, I'd say.
@akloeckner
> Support multiple entities in charts

- scripts/controllers/main.js
Since date was left in the string form (as it comes from the API), the
local date formatting was not applied in the graph (in a tooltip).
@akloeckner
> Fix date formatting in the graph

- scripts/init.js
On a small phone display the y-axis legend was crammed with values:
Changed to show less "ticks" so that everything looks nicer (on a big screen things look good also).
That value matches what Homeassistant uses (as it also uses Chart.js) so it should be just fine.
@akloeckner
> Improve y-axis legend when on small display

- index.html
- scripts/controllers/main.js
Panning provides much better and fluid experience and is easier to discover.
I'm quite happy with this change - been using it for some time myself.
There is one thing worth noting about this implementation and related side effect.
On panning, page position is updated (through CSS transform) manually to follow finger motion.
On lifting the finger, I'm finishing the movement using CSS transition.
While that makes implementation much simpler, there is a slightly noticeable "hickup" when that transition happens. It looks a bit like a frame drop. That part could be improved but it would require some fancy math formula to calculate the acc/deceleration of transition instead of relying on CSS transitions. So I'm not sure how worth it is.
Maybe try yourself and check if it's bothersome (now that …
> Toggle pages with panning instead of swiping

- scripts/controllers/main.js
Trigger history popup on long press if entity doesn't have any other handler.
I think it makes sense but you decide.
I like to be able to see history for tiles like "gauge" or even "switch" to be able to see historical/usage data.
@akloeckner
> Trigger popup history on long press if no other handlers

- index.html
- scripts/controllers/main.js
The issue happened only in browsers that didn't support pointer
events. With pointer events browser cancels events when view is
scrolled but with touch events that doesn't happen and we have
to emulate that ourselves.
Should fix issues with panning while scrolling in IOS and Firefox.
Resolves #323
@akloeckner
> Fix panning triggering during scroll

- scripts/models/api.js
end_time was assumed to be one day after after startDate by HA. providing end_time=now() explicitly fixes this.
see https://community.home-assistant.io/t/tileboard-new-dashboard-for-homeassistant/57173/2815
> fix issue, where only one day of history shown

- TILE_EXAMPLES.md
- index.html
- scripts/controllers/main.js
- scripts/directives.js
A separate camera entity id can now be specified for fullscreen cameras, for example to show a high resolution rtsp stream on the popup, while the camera thumbnail tile uses a low resolution and low bandwidth still image sequence. If the id is not specified in the fullscreen object, then the tile item id is used by default, providing backwards compatibility.
The HLS buffer default length was reduced from 30 to 5 seconds to reduce latency, and can optionally be co figured from config.js. If bufferLength is not supplied, 5 seconds are used by default.
Usage:
`
fullscreen: {
type: TYPES.CAMERA_STREAM,
ObjFit: 'contain',
id: 'camera.highres_camera',
bufferLength: 3
}
`
> A different camera entity id and hls buffersize can now be specified

- scripts/directives.js
When serving TileBoard on a different url then HA API, HLS video streams are not working. 
Added the CONFIG.serverUrl to fix this issue
> Use config serverUrl for HLS video stream

- manifest.webmanifest
iOS 13 requires not only the `"apple-mobile-web-app-capable"` meta tag but also either one of the entries `"display": "standalone"` or `"display": "fullscreen"` in the manifest file. Otherwise the "Add to Home Screen" function only creates a link to TileBoard which opens the interface in Safari. With the manifest "display" entry it behaves more like a "progressive web app", hiding the browser UI and address bar.
https://developer.mozilla.org/en-US/docs/Web/Manifest/display
> Fix for "Add to Home Screen" feature on iOS 13

- scripts/controllers/main.js
As it seems, the first data point can likely be `undefined`.
As long as this point is in the history scope, the data is handled as categorial.
Using the last data point should improve this.
It will return linear at least statistically more often for linear data..
> Improve category/linear decision on history data

- config.example.js
- styles/main.css
- styles/main.less
Something we could do to address #385. At least for browsers that support pointer-events.
People would have to update their configs for this to be effective.
Not sure what implications changing from padding to margin can have on the header but seems to work in my layout at least.
Resolves #385
> Fix clicking menu on the left through the header

- styles/main.css
- styles/main.less
My old iPad would be confused by the two definitions of popup-container and it would always display the history popup fullsize. Now it's less cluttered and unambiguous.
> clean up popup-related styles and fix size issue

- README.md
- index.html
- scripts/controllers/main.js
When setting up popups, I came across the fact that many many tiles actually had the very same content. I fixed that up into one tile template. Basically not much changes, but the code gets much smaller and simpler. 
In this course, I also removed one superfluous function, because the existent and more generic function `itemField` could be used instead.
Things that do change:
* all simple tiles have `customHtml` option now.
* the customHtml option additionally accepts templates now.
> Simplify HTML by combining all "simple" tiles into one template

- styles/main.css
- styles/main.less
The CSS solution, while probably only compatible with newer browsers,
doesn't introduce a horrible issue where switching pages makes them
have an extra offset added on top.
Resolves #415
> Replace horrible hack for disabling scrollbar with CSS

- CONTRIBUTING.md
- package-lock.json
- package.json
Sorry for the stream of changes. Just wanted people who are interested to get notified of what I'm doing.
This change will allow using `npm run release` to create a new release, which will figure automatically based on commit messages what the new version number should be and such.
> chore(release): use "npm run release" for releasing

- scripts/controllers/main.js
While browsing the code, I found this unused function...
Actually, I missed removing that function, when restructuring the door entry popup.
> chore: remove unused getEntryCameraEntity

- scripts/controllers/main.js
> fix: don't cache icon background

- index.html.ejs
- scripts/controllers/main.js
- scripts/globals/constants.js
- styles/main.less
This cleans up slider code and uses the new `cacheInItem` 
BREAKING CHANGE: The order of attrs and def is changed for a few sliders. This should not normally be a problem, because user would only use one of the possibilities. But... just to give note on that.
> refactor: cache sliders and unify handling of them

- .eslintrc.yaml
- README.md
- TILE_EXAMPLES.md
- index.html.ejs
- scripts/controllers/main-utilities.js
- scripts/controllers/main.js
- scripts/globals/constants.js
- scripts/globals/utils.js
This is a behavior change since now even if the user doesn't define
sliders and the light supports color change, then picker will still show up
on long press.
We maybe should leave support for "item.colorpicker" to be able to
override it to "false" but not sure if it's worth it.
@akloeckner
> fix(LIGHT): show color picker based on feature check

- .eslintrc.yaml
- scripts/controllers/main.js
Using ES2020's nullish coalescing operator `??`. It is just like `||`, but it only falls back to the next default, if the left operand is `null` or `undefined`. It also allows `NaN`, that's why the code becomes a bit more complex.
I tested with this input_number:
```
input_number:
test_slider:
name: Dummy for TileBoard
min: -10
max: 10
step: 1
mode: box
```
And this slider:
```
{
position: [2, 2],
id: 'input_number.test_slider',
type: TYPES.SLIDER,
state: false,
slider: {
max: 10,
min: -10,
step: 1,
}
},
```
The new code is at least useful for the `min` and `max` values, because those were not used if set to `0`. It fell back to the `attributes` then. 
I also tested the issue from #464 and don't seem to be quite able to reproduce. I did notice, however, that setting the slider to `zero` …
> fix: sliders to allow zero values

- README.md
- scripts/controllers/main.js
- scripts/globals/constants.js
- styles/main.less
also introduce the option to disable actions by setting `action: false` or `secondaryAction: false`
also show "clickable" tick not for fixed tile types, but for tiles with `action` defined
> refactor: move default actions to TILE_DEFAULTS

- .eslintrc.yaml
- package.json
- scripts/controllers/main.js
The rule is disabled for properties as the HA API requires to pass
non-camelcase keys sometimes.
> chore: enable camelcase eslint rule

- scripts/controllers/main.js
- scripts/globals/constants.js
Also, show "hvac_action" attribute by default in the subtitle as, when
available, it shows the current state of the climate device which should
be quite useful.
Resolves #526
> fix(CLIMATE): fix climate state toggle not showing up in hvac mode

- package.json
- scripts/controllers/main-utilities.js
- scripts/controllers/main.js
- scripts/globals/constants.js
- styles/main.less
- yarn.lock
This will let the user overwrite default popup layouts. And it makes the code more readable.
> fix: improve handling of merging defaults for popup tiles

- scripts/directives.js
Non HLS compatible devices, like old generation iPads, could try to "stream" video using internal browser capabilities, like Safari in iOS.
Camera Stream not working on legacy iPad:
Using `video` tag attributes directly works:
Example config:
```js
{
position: [0, 0],
width: 3,
height: 2,
bgSize: "cover",
state: false,
type: TYPES.CAMERA_THUMBNAIL,
refresh: 5000,
id: "camera.backyard",
fullscreen: {
type: TYPES.CAMERA_STREAM,
noHls: true,
objFit: "contain",
id: "camera.backyard",
bufferLength: 5,
},
}
```
> fix(CAMERA_STREAM): support non-HLS-capable devices

- index.html.ejs
- scripts/directives.js
Implemented in a way where the playback is stopped when "freezed" (should be "frozen") is `true` and after 5s, if "freezed" doesn't become `false`, the stream is stopped completely.
The stream playing in a popup is only stopped on screensaver activation (as pages can't be changed in that case), while the stream tiles are stopped on screensaver and page change.
Resolves #541
> fix(CAMERA_STREAM): pause stream when screensaver active or page changed

- scripts/controllers/main-utilities.js
The merged tile has to be re-assigned in place of the original tile as merging creates a new object reference.
> fix: merge default tile values correctly

- .github/workflows/on_release.yaml
We still need to wait for the new version of `marvinpinto/action-automatic-releases` being released but this prepares us to use the new version once it released. It can wait here until the dependency is updated.
> chore(ci): update version of the release action

- scripts/controllers/main-utilities.js
- scripts/controllers/main.js
We've overlooked the fact that user can pass a newly created tile object
to $scope.showPopup() in which case the tile defaults were not merged.
Explicitly merge defaults from the showPopup() call but avoid doing it
multiple times for tiles that have already had defaults merged by
checking a special cache key.
Fixes #553
> fix(POPUP): merge tile defaults when passing newly created tile object

- scripts/controllers/main.js
This little change will ensure that both Yandex and MapBox map images do not exceed allowed sizes. Unfortunately both of the providers (unlike Google) are throwing errors instead of simply displaying max allowed size.
> Enhancements to DEVICE_TRACKER tile

- scripts/controllers/main.js
When a history tile is shown 24/7 on a dashboard, new entries get added, but the initial start date never moves forward.
As a result, data piles up, and the initial requested offset increases constantly. After days/weeks, huge amount of data stored in the dataset can cause issues on the client side.
This small change will constantly update the start date and delete any data that is older than (NOW - OFFSET).
Shown time frame will constantly be moving forward.
In some particular cases, especially when entity states get updated rarely (only a few times a day, or even week), the history tile will no longer show any value after a while. (=> moving time window).
Hassio itself has this issue and a workaround is described here: https://community.home-assistant.io/t/add-force-update-support-to-tem …
> fix: update history tile's start date on state change

- README.md
- TILE_EXAMPLES.md
- styles/weather-icons.css
- Don't override background-repeat property set form '.wu' class
- Center weather icon in case it's smaller than expected
> fix(WEATHER): minor fixes for weather icon

- rollup.config.js
> fix: don't include empty custom.css in the release

- scripts/directives/clock.js
- scripts/directives/date.js
- scripts/directives/headerItem.html
- styles/main.less
This makes clock directive use time formatting from the currently loaded
locale. Also refactored it to be a bit cleaner.
Also fallback to locale date for HEADER.DATE/DATETIME. But since the
example config has formatting explicitly defined, this will probably
have no effect on existing configurations.
> fix(clock): show locale-formatted time

- scripts/controllers/main.js
- scripts/directives/tile.html
Makes `Slider Tile` Value more dynamic. 
Currently `Value` for `Slider` Tile not changing during slider movement. It changes only if slider released. With this change `value` become dynamic - it changes during slider move, and doesnt wait slider released, so it means you can see actual slider value. 
Also, it saves ability to use `filter` that applied to `Value`.  
Example:
```
{
position: [2, 0],
height: 2,
id: 'light.f1_r2_light_tv_wall',
type: TYPES.SLIDER,
unit: '%',
title: '',
state: false,
bottom: true,
filter: function (value) {
var num = parseFloat(value) / 2.55 ;
return num && !isNaN(num) ? num.toFixed() : 0;
},
value: '@attributes.brightness',
slider: {
max: 255,
min: 0,
step: 5,
field: 'brightness',
request: {
type: "call_service",
domain: "light",
service: "turn_on",
field: …
```
> fix(SLIDER): update value in real-time on change

- scripts/directives/headerItem.html
The "entity" is undefined in those cases so we have to pass empty
object instead like places above do already.
> fix(SCREENSAVER): fix console errors when using weather tile

- scripts/controllers/main.js
The item passed to $scope.openDoorEntry() needs to be merged with
defaults so that the layout items get "action" assigned. This is done
from the $scope.openPopup() a bit later but needs to be done before
creating the popup layout. Merging defaults will be a no-op if defaults
are already merged which will be the case when just clicking a DOOR_ENTRY
tile defined in the config.
Also done the same for other types of popups. That's not strictly
necessary right now but could become necessary in the feature if the
defaults are changed.
> fix(DOOR_ENTRY): non-clickable items when opening popup programmatically

- TILE_EXAMPLES.md
- config.example.js
- styles/weather-icons.less
> fix(WEATHER, WEATHER_LIST): replace darksky with openweathermap in examples

- package.json
- rollup.config.js
- scripts/controllers/main.js
- scripts/globals/utils.js
- scripts/init.js
- yarn.lock
> fix(locales): make moment follow the locale set in the config

- README.md
- scripts/globals/constants.js
- scripts/globals/utils.js
* use the default `filter` option for sensors
* parse with `timeAgo` in case we have a timestamp
* include the word `ago`, because timestamps are indeed ago
* add hint how to exclude the word `ago` for the uptime sensor
Localization should be handled separately, and globally for all places where `moment` is used.
In order to allow the user to profit from this further localization, `moment()` should be then be made available by `utils.js`.
closes #671
> feat: support sensors which are timestamps (like uptime sensor)

- README.md
- rollup.config.js
Including an empty file makes it annoying for people who have created
a custom "custom.css" file as then they need to take care not to
overwrite their copy.
> fix: don't include custom.css in the release

- scripts/directives/cameraStream.js
Appears to be a regression in v1 of hls.js. An upstream issue created
at https://github.com/video-dev/hls.js/issues/3732
But I also found similar issue (https://github.com/video-dev/hls.js/issues/2473)
that seems to suggest that it's best to just re-initialize the Hls
instance instead of re-attaching the media so I'll just go with that
for now.
Fixes #688
> fix(CAMERA_STREAM): stream fails to resume after being suspended

- scripts/directives/cameraStream.js
"$scope.$watch('entity', requestStream)" requested the stream and
started playing the stream even when "frozen" was true. Refactored a bit
to fix that. The code is getting kinda messy but whatever.
> fix(CAMERA_STREAM): fix frozen streams playing on load

- README.md
- TILE_EXAMPLES.md
- scripts/directives/tile.html
- scripts/globals/constants.js
This has small potential to break user's values but only slight because
if the value doesn't contain formatting patterns then it will be just
left unchanged. So if users are currently formatting the date manually,
they should see no change.
> fix(WEATHER_LIST): format date column using date filter

- README.md
- scripts/controllers/main.js
When implementing some custom, automatic layout that needs to
recalculate positions and/or sizes on items being added or removed
dynamically a hook like this one might be useful.
This is actually for my own custom layout that I'm using to position
and size items automatically but it could be useful for others too.
> feat: onLayout hook triggered on items being added/remove

- scripts/directives/tile.html
I noticed, my dimmable light shows the dim controls, even when it is `unavailable`.
> fix(LIGHT): show brightness control only when on

- scripts/directives/clock.js
On one of my devices, the undefined postfix from 24-h-format would be displayed as `undefined`.
This is the fix.
I also removed the templates from the HTML part, because they don't seem to used.
> fix(CLOCK): suppress undefined postfix

- scripts/globals/constants.js
Apparently, the new localization features convert the `label` of the `tooltipItem` to something local.
This results in something like `Mai 23, 2021, 1:03:51`, for me in German. If we try to convert that using `timeAgo`, it fails.
The fix uses the raw `dataset[].data[].x`, which is `Sun May 23 2021 01:03:51 GMT+0200 (Mitteleuropäische Sommerzeit)` in my case. This value can be converted to a time ago properly.
> fix(HISTORY): fix tooltip time for some locales

- scripts/directives/tile.html
- scripts/globals/constants.js
Take into account the new "supported_color_modes" attribute when
checking if light supports brightness adjustment.
Fixes #743
> fix(light): fix light brightness adjustment buttons after HA update

- README.md
- index.html.ejs
- scripts/controllers/main.js
- styles/main.less
- styles/themes.less
Adds a global footer, with functionality that matches the header.
Looks like vscode or the pre-commit hook re-formatted a bunch of `main.less` 🙁
Haven't contributed to this project in a few years (the pre-rollup days) so please let me know if anything needs adjusted.
> Add footer, matching functionality of header

- manifest.webmanifest
This is a requirement for installable web APKs. See #822 and criteria in https://github.com/resoai/TileBoard/issues/819#issuecomment-1059559336 .
> fix(webmanifest): add start_url
